{% set name = "nwbinspector" %}
{% set version = "0.4.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 651285db6cba872b3bd68003c072af904fdc72b759c372c4c66a2c09e3edfe42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - nwbinspector = nwbinspector.nwbinspector:inspect_all_cli

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - click
    - jsonschema
    - natsort
    - pynwb
    - PyYAML
    - tqdm
    - isodate

test:
  requires:
    - pytest
    - pytest-cov
  source_files:
    - tests
  imports:
    - nwbinspector
  commands:
    - pytest

about:
  home: https://github.com/NeurodataWithoutBorders/nwbinspector
  summary: Tool to inspect NWB files for best practices compliance
  description: |
    Inspect NWB files for compliance with NWB Best Practices.  This inspector
    is meant as a companion to the pynwb validator, which checks for strict
    schema compliance.  In contrast, this tool attempts to apply some common
    sense to find components of the file that are technically compliant, but
    probably incorrect, or suboptimal, or deviate from best practices.  This
    tool is meant simply as a data review aid.  It does not catch all best
    practice violations, and any warnings it does produce should be checked by
    a knowledgeable reviewer.
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  doc_url: https://nwbinspector.readthedocs.io
  dev_url: https://github.com/NeurodataWithoutBorders/nwbinspector

extra:
  recipe-maintainers:
    - jwodder
    - yarikoptic
    - CodyCBakerPhD
